---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-Template-Plugin-JSON-Moo
no_index:
  directory:
    - t
    - inc
    - lib/Template
requires:
  Carp: '0'
  JSON: '2.12'
  Moo: '1'
  Template: '2.20'
  Type::Tiny: '1.000006'
  namespace::clean: '0'
  perl: '5.008001'
resources:
  repository: https://github.com/tehmoth/Alt-Template-Plugin-JSON-Moo.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
